### PR TITLE
[DEVOPS] Allow "all" verbs in commit message

### PR DESCRIPTION
**Pull request by itislu**
No hard coded whitelist anymore - now "all" verbs are allowed - as long as they are "Capitalized".

### CODE REVIEW

**Review by leske42 — CHANGES_REQUESTED** [review]
this doesnt work properly lol

**Comment by itislu** [comment]
@leske42 Give me a proper feedback, I have no clue what doesn't work properly
lol

**Comment by leske42** [comment]
@itislu who hurt you

**Comment by itislu** [comment]
@leske42 Please help me fix it.

**Review by leske42 — APPROVED** [review]
Thank you its a serious quality of life improvement
P.S. @LeaYeh pls boss merge quickly

**Comment by leske42** [comment]
but what if they delete the repo

**Review by leske42 — APPROVED** [review]

**Review by LeaYeh — APPROVED** [review]

**Comment by leske42** [comment]
FREEDOM

**Pull request merged**
