### PR TITLE
[FEAT] Add sigint to shoutdown program

### PR DESCRIPTION
**Pull request by LeaYeh**
Before the testing I realized I need a way to shout down our server. 

@leske42 the signal master it's time to teach us how to handle the signal gracefully XD

### CODE REVIEW

**Review by leske42 — APPROVED** [review]
I'm no signal expert, i used to throw exceptions from handlers... no kidding
Anyway this seems to be safe & is working for me. But i noticed `uncatchable_exception_handler` in `main.cpp`, i think if you wrap everything in a try catch block for all types of `std::exception` (like you do now) then you do not need this. Afaik no function will throw an int etc unless you do it yourself. But in case you say better be safe than sorry, you would still need to move it above/inside the `try` block for it be registered.

**Review by yenthing — APPROVED** [review]
LGTM

**Comment by LeaYeh** [comment]
@leske42 Updated the condition

**Review by leske42 — APPROVED** [review]
Seems perfect. Even pure `throw;` is caught. Nothing can kill it now lol
But why do we catch sigterm? is there something specific about that signal?

**Comment by LeaYeh** [comment]
@leske42 Idk what I was thinking....

**Pull request merged**
