### PR TITLE
[DEVOPS] Add devcontainer to synchronize same env as campus

### PR DESCRIPTION
**Pull request by LeaYeh**
It also includes vscode extensions.
e.g. macOS has different system call impl. and header.

### CODE REVIEW

**Comment by LeaYeh** [comment]
@yenthing @leske42 Ready to ship.

**Review by yenthing — COMMENTED** [review]
Mine sent error too :(

**Review by leske42 — COMMENTED** [review]
Tried it according to the document on my windows laptop. It builds since 60 minutes still not done 😭 idk what im doing wrong but why we need this container for me webserv works fine in wsl

**Comment by LeaYeh** [comment]
> Tried it according to the document on my windows laptop. It builds since 60 minutes still not done 😭 idk what im doing wrong but why we need this container for me webserv works fine in wsl

Seems like only me need it, I need valgrind to test memory leaks. I tried to install valgrind on my macos, but it crash my os and I need to reinstall it...

**Comment by LeaYeh** [comment]
> Mine sent error too :(

What is the error message look like?

**Review by yenthing — APPROVED** [review]

**Comment by leske42** [comment]
@LeaYeh `Merge branch 'main' into devops-vs-devcontainer` is automatic commit msg from github. I think would be nice if tester accepted the format of these so then we can use the big buttons without conflict, but its up to you

**Comment by LeaYeh** [comment]
@leske42 and @yenthing 

For me, as a project manager, this is a philosophical issue. I understand that git merge is more intuitive than git rebase, but maintaining an elegant and maintainable history is more important.

Check the operation guide here.
https://github.com/LeaYeh/webserver/blob/main/doc/colaberate_policy.md#step-2

image

----

Explanation from ChatGPT,

In Git workflows, both git rebase and git merge are commonly used tools for integrating branches, but they function differently and produce different results. When working on a non-collaborative branch (such as a personal development branch), choosing to use git rebase main instead of git merge main often has advantages.

How git rebase and git merge Work
git rebase main:

Rebase takes the commits from your current branch and places them on top of the latest state of the main branch, effectively refreshing the history of your current branch.
Essentially, it temporarily stores your commits from the non-collaborative branch (e.g., feature-branch), resets the branch to the latest commit of main, and then re-applies your commits on top.
This produces a linear history with no branching and merge commits, making the history appear cleaner.
git merge main:

Merge takes the latest state of the main branch and integrates it with the current branch, creating a merge commit.
This preserves the history of both branches and introduces a new commit to record the merge operation.
Why Use git rebase main on Non-Collaborative Branches
Clean Commit History:

Advantage of rebase: Using git rebase results in a linear history, making it easier for other developers to track the changes of each feature or fix without the clutter of merge commits. This is especially useful on non-collaborative branches, like personal development branches.
Disadvantage of merge: Using git merge creates merge commits, which can complicate the history, particularly if there are multiple merges, making it harder to read.
Avoid Unnecessary Merge Commits:

Advantage of rebase: If you frequently update your non-collaborative branch from main, rebase helps avoid generating multiple merge commits, keeping the change history clean.
Disadvantage of merge: Every merge creates a new merge commit, which can clutter the history and make it more cumbersome when eventually merging back into main.
Easier Change Review:

Advantage of rebase: When you create a pull request after a rebase, the clean history makes it easier for reviewers to see exactly what changes you made without being distracted by a series of merge commits.
Disadvantage of merge: If there are multiple merge commits, reviewers may need to spend extra effort distinguishing between merge operations and actual changes, which can reduce review efficiency.
Preventing Code Conflicts:

Advantage of rebase: Rebase allows you to resolve conflicts earlier within your non-collaborative branch, rather than delaying conflict resolution until the final merge. This helps prevent larger conflicts when merging into main.
Disadvantage of merge: With merge, conflicts are usually postponed until the final merge operation, potentially causing unexpected issues when handling the pull request.
Potential Risks of Using git rebase
Complexity: Rebase rewrites commit history, which may confuse developers unfamiliar with Git operations. Additionally, if your non-collaborative branch has already been shared with others, rebasing can cause issues with their local repositories since the commit history has changed.

Risk of Data Loss: If something goes wrong during the rebase process and is not handled carefully, you might lose some commits. Therefore, it’s essential to ensure that your changes are safely stored and that important branches are backed up before performing a rebase.

Advantages of Using git merge
Stability: Merge does not rewrite commit history, making it generally safer than rebase in team collaboration settings. It preserves all historical information without the risk of data loss.

Preserving Full History: Sometimes, retaining the history of branch merges is intentional, as it allows team members to see how each change was progressively integrated.

Conclusion
On non-collaborative branches, using git rebase main is often a better choice as it keeps the commit history clean, makes the review process smoother, and avoids unnecessary merge commits. However, rebase should be used with caution, especially in collaborative environments. When you're in a team setting and don't want to alter the commit history, git merge might be the safer option.

**Comment by LeaYeh** [comment]
@leske42 @yenthing Let's keep our commit history as a cute small ear 👂👂👂👂

**Comment by LeaYeh** [comment]
@itislu This is another reason I just found out recently. 
```Rebase allows you to resolve conflicts earlier within your non-collaborative branch, rather than delaying conflict resolution until the final merge. This helps prevent larger conflicts when merging into main.```

Consider this image, the conflict wont showup in merge button
image

**Comment by LeaYeh** [comment]
@yenthing Can you screenshot the error on your machine?

**Comment by yenthing** [comment]
> @yenthing Can you screenshot the error on your machine?

Yes I will try it on my mac today and let you know

**Review by yenthing — APPROVED** [review]

**Comment by yenthing** [comment]
So when I tried to run "Dev Containers: Rebuild and reopen in Container", it jumped to another window and showed this error:

Screenshot 2024-09-09 at 21 14 08

**Review by leske42 — APPROVED** [review]

**Pull request merged**
