### PR TITLE
[FIX] Fix the makefile for the relink issue

### PR DESCRIPTION
**Pull request by LeaYeh**

### CODE REVIEW

**Comment by leske42** [comment]
Did it really relink though

**Comment by LeaYeh** [comment]
It was kind of recompiled, bc the mv make the target file missing, should use cp

**Comment by LeaYeh** [comment]
Cmake is quite sensitive

**Comment by leske42** [comment]
> It was kind of recompiled, bc the mv make the target file missing, should use cp

Maybe we could make it check for object files in build folder and executable at root instead of doing copy, cause like this we have 2 executable. but i dont know much about cmake

**Review by yenthing — APPROVED** [review]

**Comment by LeaYeh** [comment]
@leske42 Check it, now we dont need mv or cp anymore

**Comment by leske42** [comment]
> @leske42 Check it, now we dont need mv or cp anymore

Seems cool. But i noticed it doesnt remake if i remove object files. I mean as long as there is nothing changed in the code its fine but it might be hard to defend during eval

**Review by leske42 — APPROVED** [review]

**Pull request merged**
