### PR TITLE
[DOCS] Add state-machine definition and on going code

### PR DESCRIPTION
**Pull request by yenthing**
I'm still working on the code, so it's not fully done yet

### CODE REVIEW

**Comment by LeaYeh** [comment]
When you be at campus this week, I want to discuss this PR with you.

**Comment by yenthing** [comment]
Sure tmr I’ll be in campus around 10

**Comment by LeaYeh** [comment]
My code be overwrited from previous time😢
So now the checker still has bug

**Comment by yenthing** [comment]
But you wanna discuss about the docs or code or just general opinion? Im scared now 🥺

**Review by LeaYeh — CHANGES_REQUESTED** [review]
Need to update the state machine design
https://chatgpt.com/share/6bf7b27c-0e8b-4ff6-8b84-12d0dbac8ecc

**Comment by LeaYeh** [comment]
@yenthing Try to practice how to solve conflict with git rebase

**Comment by LeaYeh** [comment]
I recommend to list down all the possible cases we decide to handle with issue ticket so we can follow and write down the test script at the end of the process.

**Comment by LeaYeh** [comment]
image

**Pull request closed without merging**
