### PR TITLE
[DOCS] Update background_knowledge

### PR DESCRIPTION
**Pull request by yenthing**

### CODE REVIEW

**Comment by LeaYeh** [comment]
1. Try to describe update what of the background knowledge.
The commit message at least will be unique.
2. The branch name did not follow the naming conventions

**Review by LeaYeh — CHANGES_REQUESTED** [review]
Need to follow the convention

**Comment by LeaYeh** [comment]
Btw, need to rebase to the latest version

**Comment by yenthing** [comment]
I have created a new branch. should I delete this branch?

**Pull request closed without merging**
