### PR TITLE
[DEVOPS] Setup Nginx server as golden result and branchmark

### PR DESCRIPTION
**Pull request by LeaYeh**
Start Nginx server and check our beautiful homepage and template 🥂🥂🥂
http://127.0.0.1:8080/

image

This one is quite important, before we start to implement each submodule we need to compare our understanding with Nginx behavior.

Nginx usage:

1. Prepare Nginx
    - Use devcontainer, I already setup everything in it (Recommanded)
    - Install Nginx on your local machine
2. Check nginx config
    - I prepared a sample in file: tests/data/configs/nginx_reference.conf
    - Need to able to config for your own function
3. Start Nginx with correspond config file

testing config syntax
```bash
> nginx -t -c /workspace/tests/data/configs/nginx_reference.conf

// console output
nginx: the configuration file /workspace/tests/data/configs/nginx_reference.conf syntax is ok
nginx: configuration file /workspace/tests/data/configs/nginx_reference.conf test is successful
```

Start Nginx server with config file
```bash
> nginx -c /workspace/tests/data/configs/nginx_reference.conf
```
image

Stop Nginx server
```bash
> nginx -s stop                                              

// console output
2024/09/13 05:17:41 [notice] 8629#8629: signal process started
```

### CODE REVIEW

**Comment by LeaYeh** [comment]
What I learnt from Nginx:
1. how important the content-type is
    - I spent almost 2h to debug why the index.html did not apply CSS, and I realized if the content-type is wrong the browser can not render correctly
2. If the *.html include others resource then the browser will sent a new request about it
    - e.g. `<link rel="stylesheet" href="/css/styles.css">`
3. How to config correctly
```nginx.conf
location / {
            root /workspace/www/html;
            index index.html;
        }

        # This block is used to define the location of the css directory
        location /css/ {
            root /workspace/www;
            index styles.css;
            default_type text/css;
        }
```

**Comment by LeaYeh** [comment]
This PR might raise issue #49

**Comment by itislu** [comment]
~branchmark~ benchmark

**Comment by LeaYeh** [comment]
With the commit https://github.com/LeaYeh/webserver/pull/48/commits/a69d658d1c6d66507daecab30d71b6385575ff4a

I exported ports in the container:
1. nginx = 4000 (also updated the config file for nginx: /workspace/configs/refs/nginx_reference.conf)
2. our web server = 8080

So with the h1spec (https://github.com/LeaYeh/h1spec/), you guys can use the easy tool to test the nginx and webserv.

```
# h1spec
cd experiments
go run easy_tool.go
```

or 
```
# h1spec
cd cmd
go run h1spec.go -h webserv_container -p 8080
```

**Review by leske42 — APPROVED** [review]
seems fine

**Review by yenthing — COMMENTED** [review]
Ok

**Review by yenthing — APPROVED** [review]

**Pull request merged**
