### PR TITLE
[DOC]: Add poll() definition

### PR DESCRIPTION
**Pull request by yenthing**
This is a test to see if I push align with your request. I still have a problem with feat-<NAME> when it comes to these commands: 
> git checkout feat-<NAME>
> git rebase main

### CODE REVIEW

**Comment by LeaYeh** [comment]
We need to check tomorrow because in the PR I can not see your commit change, those 6 commits are from mine.
Maybe you forgot to commit and push after rebase.

**Review by LeaYeh — CHANGES_REQUESTED** [review]
Commit history looks incorrect.

**Comment by yenthing** [comment]
sad ok! I can repush again. should I?

**Comment by LeaYeh** [comment]
You can try and practice ☺️

**Pull request merged**
